name: Linux-x64-GCC with OpenSSL FIPS

on:
  push:
    branches:
      - main  # 更改为您需要触发构建的分支

env:
  VERSION: '1.0.2'
  TAG: 'k'
  OPENSSL_FIPS_VERSION: '2.0.16'
  INSTALL_PREFIX: '/tmp/openssl-x64'

jobs:
  build-openssl:
    runs-on: ubuntu-20.04  # 或选择其他支持的Ubuntu版本

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential perl libssl-dev zlib1g-dev

    - name: Download and unpack OpenSSL source and FIPS module
      run: |
        wget https://www.openssl.org/source/old/$VERSION/openssl-$VERSION$TAG.tar.gz
        tar -xzvf openssl-$VERSION$TAG.tar.gz
        wget https://www.openssl.org/source/openssl-fips-$OPENSSL_FIPS_VERSION.tar.gz
        tar -xzvf openssl-fips-$OPENSSL_FIPS_VERSION.tar.gz
    
    - name: Build FIPS
      run: |
        cd openssl-fips-$OPENSSL_FIPS_VERSION
        ./config --prefix=/tmp/openssl-x64/ssl/fips-2.0.16
        make
        make install
    
    - name: Configure OpenSSL for FIPS
      run: |
        export CPPFLAGS="-I/tmp/openssl-x64/tmp/openssl-x64/ssl/fips-2.0.16/include"
        cd openssl-$VERSION$TAG
        ./config fips shared --with-fipsdir=/tmp/openssl-x64/tmp/openssl-x64/ssl/fips-2.0.16/

    - name: Build OpenSSL (including FIPS)
      run: |
        cd openssl-$VERSION$TAG
        make -j$(nproc)

    - name: Install OpenSSL
      run: |
        cd openssl-$VERSION$TAG
        make install
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: openssl-x64
        path: /tmp/openssl-x64/usr/local/ssl
