name: linux-aarch64-gcc

on:
  push:
    branches:
      - main  # 更改为您需要触发构建的分支
env:
  VERSION: '1.0.2'
  TAG: 'k'
jobs:
  build-openssl:
    runs-on: ubuntu-20.04  # 或者选择其他支持的Ubuntu版本

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-aarch64-linux-gnu perl libssl-dev zlib1g-dev

    - name: Download and unpack OpenSSL source
      run: |
        wget https://www.openssl.org/source/old/$VERSION/openssl-$VERSION$TAG.tar.gz
        tar -xzvf openssl-$VERSION$TAG.tar.gz
        wget https://www.openssl.org/source/openssl-fips-2.0.16.tar.gz
        tar xvfz openssl-fips-2.0.16.tar.gz

    - name: Configure OpenSSL for aarch64
      run: |
        cd openssl-fips-2.0.16
        chmod +x Configure
        ./Configure linux-aarch64 --prefix=/tmp/openssl-aarch64 fips shared \
                  -Wa,--noexecstack \
                  -DL_ENDIAN \
                  -DOPENSSL_USE_NODELETE \
                  -fPIC

    - name: Compile OpenSSL
      run: |
        cd openssl-fips-2.0.16
        make CC=aarch64-linux-gnu-gcc

    - name: Install OpenSSL
      run: |
        cd openssl-fips-2.0.16
        make install_sw

#    - name: Verify installation
#      run: |
#        /tmp/openssl-aarch64/bin/openssl version

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: openssl-aarch64
        path: /tmp/openssl-aarch64/
