name: linux-mips64-gcc

on:
  push:
    branches:
      - main  # 更改为您需要触发构建的分支
env:
  VERSION: 'fips-2.0.16'  # 修改为您想要编译的openssl版本
jobs:
  build-openssl:
    runs-on: ubuntu-20.04  # 或者选择其他支持的Ubuntu版本

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-mips64el-linux-gnuabi64 g++-mips64el-linux-gnuabi64 build-essential perl libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git

    - name: Download and unpack OpenSSL source
      run: |
        wget https://www.openssl.org/source/openssl-$VERSION.tar.gz
        tar -xzvf openssl-$VERSION.tar.gz

    - name: Configure OpenSSL for mips64el
      run: |
        cd openssl-$VERSION
        export CC=mips64el-linux-gnuabi64-gcc
        export CFLAGS="-mcpu=mips64r2 -Wa,--noexecstack"
        ./config --prefix=/tmp/openssl-mips64 \
                  no-shared \
                  enable-ec_nistp_64_gcc_128 \
                  -DL_ENDIAN \
                  -DOPENSSL_USE_NODELETE \
                  -fPIC

    - name: Compile OpenSSL
      run: |
        cd openssl-$VERSION
        make -j$(nproc) CC=mips64el-linux-gnuabi64-gcc

    - name: Install OpenSSL
      run: |
        cd openssl-$VERSION
        make install_sw

    - name: Verify installation
      run: |
        /tmp/openssl-mips64el/bin/openssl version

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: openssl-mips64el
        path: /tmp/openssl-mips64el/
