name: Linux-x64-GCC with OpenSSL FIPS

on:
  push:
    branches:
      - main  # 更改为您需要触发构建的分支

env:
  OPENSSL_VERSION: '1.0.2k'
  OPENSSL_FIPS_VERSION: '2.0.16'
  INSTALL_PREFIX: '/tmp/openssl-x64'

jobs:
  build-openssl:
    runs-on: ubuntu-20.04  # 或选择其他支持的Ubuntu版本

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential perl libssl-dev zlib1g-dev

    - name: Download and unpack OpenSSL source and FIPS module
      run: |
        wget https://www.openssl.org/source/old/$OPENSSL_VERSION/openssl-$OPENSSL_VERSION.tar.gz
        tar -xzvf openssl-$OPENSSL_VERSION.tar.gz
        wget https://www.openssl.org/source/openssl-fips-$OPENSSL_FIPS_VERSION.tar.gz
        tar -xzvf openssl-fips-$OPENSSL_FIPS_VERSION.tar.gz

    - name: Configure OpenSSL for FIPS
      run: |
        cd openssl-$OPENSSL_VERSION
        ./config --prefix=$INSTALL_PREFIX shared \
                  -I../openssl-fips-$OPENSSL_FIPS_VERSION/include \
                  -L../openssl-fips-$OPENSSL_FIPS_MODULE/lib \
                  -Wa,--noexecstack \
                  -DL_ENDIAN \
                  -DOPENSSL_USE_NODELETE \
                  -fPIC \
                  enable-fips

    - name: Build OpenSSL (including FIPS)
      run: |
        cd openssl-$OPENSSL_VERSION
        make depend
        make -j$(nproc)

    - name: Install OpenSSL
      run: |
        cd openssl-$OPENSSL_VERSION
        make install_sw

    - name: Create pkg-config files (optional)
      run: |
        cp $INSTALL_PREFIX/lib/pkgconfig/* $INSTALL_PREFIX/share/pkgconfig/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: openssl-x64
        path: $INSTALL_PREFIX/
